# Generated by Django 6.0.2 on 2026-03-28 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ACADEMICS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('home_address', models.CharField(default='Not Provided', max_length=200)),
                ('guardian_name', models.CharField(default='Not Provided', max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('guardian_contact', models.CharField(default='0000000000', max_length=15)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ACADEMICS.classsection')),
                ('enrolled_subjects', models.ManyToManyField(related_name='enrolled_students', to='ACADEMICS.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
