# Generated by Django 6.0.2 on 2026-03-28 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ACADEMICS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('classes', models.ManyToManyField(related_name='teachers', to='ACADEMICS.classsection')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='ACADEMICS.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
