# Generated by Django 6.0.2 on 2026-03-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(default='Main Hall', max_length=100)),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_possible_mark', models.IntegerField(default=100)),
                ('percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('remark', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Blue' or 'A'", max_length=20)),
                ('grade_level', models.PositiveSmallIntegerField(choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3'), (4, 'Form 4'), (5, 'Lower Sixth'), (6, 'Upper Sixth')], default=1)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Class Section',
                'verbose_name_plural': 'Class Sections',
                'ordering': ['grade_level', 'name'],
                'unique_together': {('name', 'grade_level')},
            },
        ),
    ]
