# Generated by Django 6.0.2 on 2026-03-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='My School Portal', max_length=255)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_info/')),
                ('motto', models.CharField(blank=True, max_length=500)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('mascot_name', models.CharField(blank=True, max_length=100)),
                ('postal_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
    ]
